# nginx proxy address - http://172.17.0.1:59041

name: onedev
x-logging: &default-logging
  options:
    max-size: '5m'
    max-file: '1'
  driver: json-file

services:
  app:
    image: 1dev/server:latest
    container_name: onedev-app
    hostname: ${BASE_HOST_NAME:-$HOSTNAME}
    restart: always
    pull_policy: always
    logging: *default-logging
    environment:
      TZ: ${TZ:-America/New_York}
      initial_server_url: https://${BASE_HOST_NAME:-$HOSTNAME}
      initial_user: ${APP_ADMIN_USER:-administrator}
      initial_password: ${APP_ADMIN_PASS:-changeme_admin_password}
      initial_email: ${APP_ADMIN_USER:-administrator}@${BASE_DOMAIN_NAME:-example.com}
      CONTAINER_NAME: onedev-app
      HOSTNAME: ${BASE_HOST_NAME:-$HOSTNAME}
    ports:
      - '172.17.0.1:59041:6610/tcp'
    volumes:
      - './volumes/data/onedev:/opt/onedev:rw'
      - '/etc/timezone:/etc/timezone:ro'
      - '/etc/localtime:/etc/localtime:ro'
      - '/var/run/docker.sock:/var/run/docker.sock:ro'
    healthcheck:
      test: timeout 10s bash -c ':> /dev/tcp/127.0.0.1/6610' || exit 1
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 90s
    networks:
      - onedev
      - proxy
      - cloudflare
    labels:
      - 'traefik.enable=true'
      - 'cloudflare.enable=true'
      - 'traefik.docker.network=proxy'
      - 'cloudflare.service=http://onedev-app:6610'
      - 'cloudflare.hostname=onedev.${CLOUDFLARE_ZONE_NAME:-}'
      - 'traefik.http.routers.onedev-app.entrypoints=http'
      - 'traefik.http.routers.onedev-app-secure.tls=true'
      - 'traefik.http.routers.onedev-app.rule=Host($(${BASE_HOST_NAME:-$HOSTNAME}))'
      - 'traefik.http.middlewares.onedev-app-https-redirect.redirectscheme.scheme=https'
      - 'traefik.http.routers.onedev-app.middlewares=onedev-app-https-redirect'
      - 'traefik.http.routers.onedev-app-secure.entrypoints=https'
      - 'traefik.http.routers.onedev-app-secure.rule=Host($(${BASE_HOST_NAME:-$HOSTNAME}))'
      - 'traefik.http.routers.onedev-app-secure.tls.certresolver=cloudflare'
      - 'traefik.http.routers.onedev-app-secure.service=onedev-app'
      - 'traefik.http.services.onedev-app.loadbalancer.server.port=6610'

networks:
  onedev:
    name: onedev
    external: false
  proxy:
    external: true
  cloudflare:
    external: true
